plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

compose.resources {
    generateResClass = always
}

kotlin {
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "mssimulator.js"
            }
        }
        binaries.executable()
    }

    jvm("desktop")

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
            }
        }

        val wasmJsMain by getting {
            dependencies {
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

/**
 * Generates SampleData.kt from data/skills.json and data/bosses.json at build time.
 * This ensures the app always reflects the latest data files.
 * Update data/*.json → rebuild → app uses new data.
 */
val generateSampleData by tasks.registering {
    description = "Generate SampleData.kt from data/skills.json and data/bosses.json"
    group = "build"

    val dataDir = rootProject.projectDir.resolve("data")
    val sampleDataFile = projectDir.resolve("src/commonMain/kotlin/com/mssimulator/data/SampleData.kt")

    inputs.dir(dataDir)
    outputs.file(sampleDataFile)

    doLast {
        val skillsJson = dataDir.resolve("skills.json").readText()
        val bossesJson = dataDir.resolve("bosses.json").readText()

        val tq = "\"\"\""
        val content = buildString {
            appendLine("// AUTO-GENERATED by generateSampleData task — do not edit manually")
            appendLine("// To update: edit data/skills.json or data/bosses.json, then rebuild")
            appendLine("package com.mssimulator.data")
            appendLine()
            append("val SAMPLE_SKILLS_JSON = ")
            append(tq)
            append(skillsJson)
            append(tq)
            appendLine()
            appendLine()
            append("val SAMPLE_BOSSES_JSON = ")
            append(tq)
            append(bossesJson)
            append(tq)
            appendLine()
        }

        val existing = if (sampleDataFile.exists()) sampleDataFile.readText() else ""
        if (existing != content) {
            sampleDataFile.writeText(content)
            logger.lifecycle("generateSampleData: regenerated SampleData.kt (${skillsJson.length + bossesJson.length} bytes of JSON)")
        } else {
            logger.info("generateSampleData: SampleData.kt is up to date")
        }
    }
}

// Wire into compile tasks
tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }.configureEach {
    dependsOn(generateSampleData)
}
